<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="projetTemplate" nsURI="http://www.example.org/projetTemplate"
    nsPrefix="projetTemplate">
  <eClassifiers xsi:type="ecore:EClass" name="DomainProblem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainRequirementValue"
        upperBound="-1" eType="#//DomainRequirementValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainRequirementValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explanation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementtype" lowerBound="1"
        eType="#//RequirementType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementmapping" lowerBound="1"
        eType="#//RequirementMapping"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueType" eType="#//RequirementTypeValues"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLProject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataanalysisproblem" lowerBound="1"
        eType="#//DataAnalysisProblem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainproblem" lowerBound="1"
        eType="#//DomainProblem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" eType="#//Database"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataAnalysisProblem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataanalysisproblemtype"
        lowerBound="1" eType="#//DataAnalysisProblemType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computationalrequirementvalue"
        upperBound="-1" eType="#//ComputationalRequirementValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mlprocchainsolutionpattern"
        eType="#//MLProcChainSolutionPattern"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputationalRequirementValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rationale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementtype" eType="#//RequirementType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Database">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credentias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" eType="#//Data"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="technology" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelelement" lowerBound="1"
        eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credentias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restrictions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rationale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementtype" lowerBound="1"
        eType="#//RequirementType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datapropertyvalueset" lowerBound="1"
        eType="#//DataPropertyValueSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datapropertyvalue" lowerBound="1"
        eType="#//DataPropertyValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyValueSet">
    <eOperations name="evaluate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="setType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datapropertyvalue" upperBound="-1"
        eType="#//DataPropertyValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datapropertytype" lowerBound="1"
        eType="#//DataPropertyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataAnalysisProblemType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="#//EnumDataAnalysisProblemType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mlalgorithmsolutionpattern"
        upperBound="-1" eType="#//MLAlgorithmSolutionPattern" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingChain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mlalgorithm" lowerBound="1"
        upperBound="-1" eType="#//MLAlgorithm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLProcChainSolutionPattern">
    <eOperations name="SelectMLAlgorithm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explanation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datapropertyvalueset" lowerBound="1"
        upperBound="-1" eType="#//DataPropertyValueSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingchain" lowerBound="1"
        eType="#//ProcessingChain"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataanalysisproblemtype"
        eType="#//DataAnalysisProblemType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SelectedProcessingChainTemplateForTheMLAlgorithm"
        lowerBound="1" eType="#//ProcessingChainTemplate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collecteddataknowledgeabouttemplateconstruction"
        eType="#//CollectedDataKnowledgeAboutTemplateConstruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingChainTemplate">
    <eOperations name="ReducedItUsingknwoledge">
      <eParameters name="param1" eType="#//CollectedDataKnowledgeAboutTemplateConstruction"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedbpmnmodel" lowerBound="1"
        eType="#//ExtendedBPMNModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        upperBound="-1" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLAlgorithmSolutionPattern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explanation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mlalgorithm" lowerBound="1"
        eType="#//MLAlgorithm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datapropertyvalueset" lowerBound="1"
        upperBound="-1" eType="#//DataPropertyValueSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLAlgorithm" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectioncriterionvalueset"
        eType="#//SelectionCriterionValueSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectioncriterionvalue"
        upperBound="-1" eType="#//SelectionCriterionValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingchaintemplate"
        lowerBound="1" eType="#//ProcessingChainTemplate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionCriterionValueSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="setType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectioncriterionvalue"
        lowerBound="1" upperBound="-1" eType="#//SelectionCriterionValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectioncriterion" lowerBound="1"
        eType="#//SelectionCriterion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionCriterionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectioncriterion" lowerBound="1"
        eType="#//SelectionCriterion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionCriterion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedBPMNModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Explainability" eSuperTypes="#//DomainRequirementValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Values1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Values1">
    <eLiterals name="Yes"/>
    <eLiterals name="No" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Values2">
    <eLiterals name="High"/>
    <eLiterals name="Moderate" value="1"/>
    <eLiterals name="Low" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RequirementTypeValues">
    <eLiterals name="Explinability"/>
    <eLiterals name="Accuracy" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Accuracy" eSuperTypes="#//DomainRequirementValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Values2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumDataAnalysisProblemType">
    <eLiterals name="Classification"/>
    <eLiterals name="Regression" value="1"/>
    <eLiterals name="Clustering" value="2"/>
    <eLiterals name="Feature_construction" value="3" literal="Feature_construction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectedDataKnowledgeAboutTemplateConstruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1" eType="#//Rule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Condition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultat" lowerBound="1"
        eType="#//Resultat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" lowerBound="1" upperBound="-1"
        eType="#//Term"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resultat">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" lowerBound="1" upperBound="-1"
        eType="#//Term"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="variable" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valeur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Term"/>
  <eClassifiers xsi:type="ecore:EClass" name="connector" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conneteur" eType="#//EnumConnector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumConnector">
    <eLiterals name="OR" literal="OU"/>
    <eLiterals name="AND" value="1" literal="^"/>
    <eLiterals name="ACCOLAD_OUVERT" value="2" literal="ACCOLAD_OUVERT"/>
    <eLiterals name="ACCOLAD_FERME" value="3" literal="ACCOLAD_FERME"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataCleaning" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataPretraitement" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureSelection" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureConstruction" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="PostTreatement" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Deployement" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveUncessaryFileds" eSuperTypes="#//DataCleaning">
    <eOperations name="removeIDs"/>
    <eOperations name="removeSpecialCharacters"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="#//RemoveUncessaryFiledsEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conversion" eSuperTypes="#//DataPretraitement">
    <eOperations name="convertCategoricalAttributesToContinue"/>
    <eOperations name="convertContinueAttributesToCategorical"/>
    <eOperations name="detectAttributeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="#//ConversionEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NoiseTreatement" eSuperTypes="#//DataPretraitement">
    <eOperations name="removeNoiseFromFileds"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="#//NoiseTreatementEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MissingValueTreatement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ConversionEnum">
    <eLiterals name="convertCategoricalAttributesToContinue" literal="convertCategoricalAttributesToContinue"/>
    <eLiterals name="convertContinueAttributesToCategorical" value="1"/>
    <eLiterals name="detectAttributeType" value="2" literal="detectAttributeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RemoveUncessaryFiledsEnum">
    <eLiterals name="removeIDs"/>
    <eLiterals name="removeSpecialCharacters" value="1" literal="removeSpecialCharacters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NoiseTreatementEnum">
    <eLiterals name="removeNoiseFromFileds" literal="removeNoiseFromFileds"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MissingValueTreatementEnum">
    <eLiterals name="ReplaceByMean"/>
    <eLiterals name="ReplaceByZero" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="NewDataType10" instanceTypeName="newDataType10"/>
</ecore:EPackage>
